---

- hosts: all
  become: true
  vars:
    user: "{{ user }}"
  tasks: 
  
  - name: install packages
    ansible.builtin.apt:
      name:
        - firefox
        - foot
        - neofetch
        - pavucontrol
        - pipewire
        - python3-pip
        - sway
        - unzip
        - waybar
        - wofi
      state: present

  - name: install pip packages
    ansible.builtin.pip:
      name:
        - pipenv
        - pywal


  - name: copy dotfiles
    ansible.builtin.copy: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644
      backup: true
    loop:
      - src: ../bashrc
        dest: "/home/{{ user }}/.bashrc"
      - src: ../config/foot/
        dest: "/home/{{ user }}/.config/foot/"
      - src: ../config/sway/
        dest: "/home/{{ user }}/.config/sway/"
      - src: ../config/waybar/config
        dest: "/home/{{ user }}/.config/waybar/config"
      - src: ../config/wofi/config
        dest: "/home/{{ user }}/.config/wofi/config"
      - src: ../cache/wal/
        dest: "/home/{{ user }}/.cache/wal"

  - name: Apply css template files
    ansible.builtin.template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - src: ../config/waybar/style.css.j2
        dest: "/home/{{ user }}/.config/waybar/style.css"
      - src: ../config/wofi/style.css.j2
        dest: "/home/{{ user }}/.config/wofi/style.css"