---

- hosts: all
  become: true
  tasks: 

  - name: install packages
    package:
      name:
        - sway
        - foot
        - wofi
        - waybar
      state: present


  - name: copy dotfiles
    ansible.builtin.copy: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644
      backup: true
    loop:
      - src: ../bashrc
        dest: "/home/{{ user }}/.bashrc"
      - src: ../config/foot/
        dest: "/home/{{ user }}/.config/foot/"
      - src: ../config/sway/
        dest: "/home/{{ user }}/.config/sway/"
      - src: ../config/waybar/
        dest: "/home/{{ user }}/.config/waybar/"
      - src: ../config/wofi/
        dest: "/home/{{ user }}/.config/wofi/"